name: Build and deploy Docker container to Azure Web App - tee-time-reservation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E088E6F8EBA24C3DAE4DAF92098BB755 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_43C07663962E45EA80EE4BC219E127B6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_21E22FDF425042158A40073676099DC4 }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          use-identity: true
          
      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/tee-time-reservation:latest
          file: ./Dockerfile
          # Add build cache settings for faster builds
          cache-from: type=registry,ref=${{ secrets.ACR_LOGIN_SERVER }}/tee-time-reservation:buildcache
          cache-to: type=registry,ref=${{ secrets.ACR_LOGIN_SERVER }}/tee-time-reservation:buildcache,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E088E6F8EBA24C3DAE4DAF92098BB755 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_43C07663962E45EA80EE4BC219E127B6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_21E22FDF425042158A40073676099DC4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tee-time-reservation'
          slot-name: 'Production'
          images: ${{ secrets.ACR_LOGIN_SERVER }}/tee-time-reservation:latest